language: python
python:
 - "2.7"
 - "3.6"

install:
  - pip install -e .
  - pip install tox-travis
  - pip install tox
  - pip install dogpile.cache<1.0.0
  
script: tox

services:
  - redis-server
